# Generated by Django 5.0.7 on 2024-07-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='x_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='y_position',
            field=models.IntegerField(default=0),
        ),
    ]
